"""
seed_demo_data — populates Carles, Iloilo demo data for NomadReady PH.

Idempotent: uses update_or_create() keyed on (destination, name) for listings
and get_or_create() keyed on name for the destination. Safe to run multiple times.

ScoreSnapshot and AIRecommendation are NOT seeded here.
They are generated by the scoring engine and AI advisor in later feature branches.

─────────────────────────────────────────────────────────────────────
LISTING DETAILS JSON SCHEMA
─────────────────────────────────────────────────────────────────────
The scoring engine (feature/scoring-engine) reads these keys from
Listing.details. Do not rename keys without updating services.py.

work_spot:
  wifi_available        bool   — has Wi-Fi
  zoom_friendly         bool   — suitable for video calls
  power_outlets         bool   — has power outlets at seats
  wifi_speed_mbps       int|null — published speed in Mbps, null if unknown
  mobile_data_available bool   — mobile signal present

accommodation:
  monthly_rate_available bool  — monthly pricing is published
  has_wifi               bool  — Wi-Fi included
  has_desk               bool  — dedicated work desk
  has_kitchen            bool  — kitchen or kitchenette
  has_laundry            bool  — laundry access

service:
  service_type    str  — "clinic" | "hospital" | "police" | "pharmacy"
                          | "atm" | "laundry" | "grocery"
  contact_available bool — has listed contact/number
  has_safety_notes  bool — safety information is documented

transport:
  route_from_iloilo bool  — is the main Iloilo City → Carles route
  is_port           bool  — is a port or ferry terminal
  local_transport   bool  — is a local in-town option
  schedule_available bool — schedule or frequency is published
  fare_info         bool  — fare/cost information is available
  travel_time_hours float|null — approximate travel time from Iloilo City

attraction:
  island_hopping    bool  — island hopping or beach activity
  has_tour_operator bool  — tour operator or guide available
  activity_type     str   — "beach" | "island" | "food" | "nature"
                             | "culture" | "wellness" | "sandbar"
  has_community_event bool — community or seasonal event associated
─────────────────────────────────────────────────────────────────────
"""

from django.core.management.base import BaseCommand
from apps.destinations.models import Destination
from apps.listings.models import Listing


CARLES_LISTINGS = [
    # ── WORK SPOTS ────────────────────────────────────────────────
    {
        "name": "Carles Port Café",
        "category": Listing.Category.WORK_SPOT,
        "type": "cafe",
        "address": "Port Area, Carles, Iloilo",
        "latitude": "11.5170",
        "longitude": "123.1150",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "wifi_available": True,
            "zoom_friendly": True,
            "power_outlets": True,
            "wifi_speed_mbps": 25,
            "mobile_data_available": True,
        },
    },
    {
        "name": "Isla Work Lounge",
        "category": Listing.Category.WORK_SPOT,
        "type": "lounge",
        "address": "Carles Town Proper, Iloilo",
        "latitude": "11.5155",
        "longitude": "123.1180",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "wifi_available": True,
            "zoom_friendly": True,
            "power_outlets": True,
            "wifi_speed_mbps": 20,
            "mobile_data_available": True,
        },
    },
    {
        "name": "Gigantes Gateway Inn Lobby",
        "category": Listing.Category.WORK_SPOT,
        "type": "hotel_lobby",
        "address": "Gigantes Islands, Carles, Iloilo",
        "latitude": "11.6600",
        "longitude": "123.1980",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "wifi_available": True,
            "zoom_friendly": False,
            "power_outlets": True,
            "wifi_speed_mbps": None,
            "mobile_data_available": True,
        },
    },
    # ── ACCOMMODATIONS ────────────────────────────────────────────
    {
        "name": "Carles Bay Homestay",
        "category": Listing.Category.ACCOMMODATION,
        "type": "homestay",
        "address": "Carles Bay Area, Iloilo",
        "latitude": "11.5140",
        "longitude": "123.1120",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "monthly_rate_available": True,
            "has_wifi": True,
            "has_desk": False,
            "has_kitchen": False,
            "has_laundry": False,
        },
    },
    {
        "name": "Gigantes Gateway Pension",
        "category": Listing.Category.ACCOMMODATION,
        "type": "pension",
        "address": "Gigantes Islands, Carles, Iloilo",
        "latitude": "11.6590",
        "longitude": "123.1970",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "monthly_rate_available": False,
            "has_wifi": True,
            "has_desk": False,
            "has_kitchen": False,
            "has_laundry": False,
        },
    },
    {
        "name": "Island Stay Carles",
        "category": Listing.Category.ACCOMMODATION,
        "type": "guesthouse",
        "address": "Carles Town Proper, Iloilo",
        "latitude": "11.5162",
        "longitude": "123.1165",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "monthly_rate_available": True,
            "has_wifi": True,
            "has_desk": False,
            "has_kitchen": False,
            "has_laundry": False,
        },
    },
    # ── SERVICES ──────────────────────────────────────────────────
    {
        "name": "Carles Municipal Health Office",
        "category": Listing.Category.SERVICE,
        "type": "clinic",
        "address": "Municipal Hall Compound, Carles, Iloilo",
        "latitude": "11.5168",
        "longitude": "123.1172",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "service_type": "clinic",
            "contact_available": True,
            "has_safety_notes": False,
        },
    },
    {
        "name": "Carles Police Station",
        "category": Listing.Category.SERVICE,
        "type": "police",
        "address": "Carles, Iloilo",
        "latitude": "11.5172",
        "longitude": "123.1175",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "service_type": "police",
            "contact_available": True,
            "has_safety_notes": False,
        },
    },
    {
        "name": "Local Pharmacy",
        "category": Listing.Category.SERVICE,
        "type": "pharmacy",
        "address": "Carles Town Proper, Iloilo",
        "latitude": "11.5160",
        "longitude": "123.1160",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "service_type": "pharmacy",
            "contact_available": False,
            "has_safety_notes": False,
        },
    },
    {
        "name": "Laundry Service",
        "category": Listing.Category.SERVICE,
        "type": "laundry",
        "address": "Carles Town Proper, Iloilo",
        "latitude": "11.5158",
        "longitude": "123.1158",
        "verification_status": Listing.VerificationStatus.DRAFT,
        "details": {
            "service_type": "laundry",
            "contact_available": False,
            "has_safety_notes": False,
        },
    },
    {
        "name": "ATM near town center",
        "category": Listing.Category.SERVICE,
        "type": "atm",
        "address": "Carles Town Center, Iloilo",
        "latitude": "11.5165",
        "longitude": "123.1168",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "service_type": "atm",
            "contact_available": False,
            "has_safety_notes": False,
        },
    },
    # ── TRANSPORT ─────────────────────────────────────────────────
    {
        "name": "Iloilo City to Carles van route",
        "category": Listing.Category.TRANSPORT,
        "type": "van_route",
        "address": "Tagbak Terminal, Iloilo City to Carles",
        "latitude": "11.5200",
        "longitude": "123.1100",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "route_from_iloilo": True,
            "is_port": False,
            "local_transport": False,
            "schedule_available": True,
            "fare_info": True,
            "travel_time_hours": None,
        },
    },
    {
        "name": "Bancal Port",
        "category": Listing.Category.TRANSPORT,
        "type": "port",
        "address": "Bancal, Carles, Iloilo",
        "latitude": "11.5210",
        "longitude": "123.1090",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "route_from_iloilo": False,
            "is_port": True,
            "local_transport": False,
            "schedule_available": True,
            "fare_info": True,
            "travel_time_hours": None,
        },
    },
    {
        "name": "Tricycle local transport",
        "category": Listing.Category.TRANSPORT,
        "type": "tricycle",
        "address": "Carles Town Proper, Iloilo",
        "latitude": "11.5163",
        "longitude": "123.1163",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "route_from_iloilo": False,
            "is_port": False,
            "local_transport": False,
            "schedule_available": False,
            "fare_info": True,
            "travel_time_hours": None,
        },
    },
    {
        "name": "Boat route to Gigantes Islands",
        "category": Listing.Category.TRANSPORT,
        "type": "boat",
        "address": "Bancal Port, Carles to Gigantes Islands",
        "latitude": "11.5215",
        "longitude": "123.1085",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "route_from_iloilo": False,
            "is_port": False,
            "local_transport": False,
            "schedule_available": True,
            "fare_info": True,
            "travel_time_hours": None,
        },
    },
    # ── ATTRACTIONS ───────────────────────────────────────────────
    {
        "name": "Gigantes Islands",
        "category": Listing.Category.ATTRACTION,
        "type": "island",
        "address": "Gigantes Islands, Carles, Iloilo",
        "latitude": "11.6650",
        "longitude": "123.2000",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "island_hopping": True,
            "has_tour_operator": True,
            "activity_type": "island",
            "has_community_event": False,
        },
    },
    {
        "name": "Cabugao Gamay Island",
        "category": Listing.Category.ATTRACTION,
        "type": "island",
        "address": "Cabugao Gamay, Gigantes, Carles, Iloilo",
        "latitude": "11.6700",
        "longitude": "123.2050",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "island_hopping": True,
            "has_tour_operator": False,
            "activity_type": "beach",
            "has_community_event": False,
        },
    },
    {
        "name": "Bantigue Sandbar",
        "category": Listing.Category.ATTRACTION,
        "type": "sandbar",
        "address": "Bantigue Island, Carles, Iloilo",
        "latitude": "11.6580",
        "longitude": "123.1900",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "island_hopping": True,
            "has_tour_operator": False,
            "activity_type": "sandbar",
            "has_community_event": False,
        },
    },
    {
        "name": "Antonia Beach",
        "category": Listing.Category.ATTRACTION,
        "type": "beach",
        "address": "Antonia, Carles, Iloilo",
        "latitude": "11.6500",
        "longitude": "123.1850",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "island_hopping": False,
            "has_tour_operator": False,
            "activity_type": "beach",
            "has_community_event": True,
        },
    },
    {
        "name": "Seafood food experience",
        "category": Listing.Category.ATTRACTION,
        "type": "food",
        "address": "Carles Public Market, Iloilo",
        "latitude": "11.5155",
        "longitude": "123.1155",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "island_hopping": False,
            "has_tour_operator": False,
            "activity_type": "food",
            "has_community_event": True,
        },
    },
]


class Command(BaseCommand):
    help = "Seed Carles, Iloilo demo data for NomadReady PH. Idempotent — safe to run multiple times."

    def handle(self, *args, **options):
        destination, created = Destination.objects.get_or_create(
            name="Carles",
            defaults={
                "province": "Iloilo",
                "municipality": "Carles",
                "description": (
                    "Carles is a municipality in the northern tip of Iloilo province, "
                    "known for the Gigantes Islands — a group of islands and islets "
                    "renowned for pristine beaches, rock formations, and rich marine life. "
                    "The pilot destination for NomadReady PH."
                ),
            },
        )

        action = "Created" if created else "Found existing"
        self.stdout.write(f"{action} destination: {destination}")

        created_count = 0
        updated_count = 0

        for data in CARLES_LISTINGS:
            listing, was_created = Listing.objects.update_or_create(
                destination=destination,
                name=data["name"],
                defaults={
                    "category": data["category"],
                    "type": data["type"],
                    "address": data["address"],
                    "latitude": data["latitude"],
                    "longitude": data["longitude"],
                    "details": data["details"],
                    "verification_status": data["verification_status"],
                },
            )
            if was_created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"\nSeed complete.\n"
                f"  Listings created: {created_count}\n"
                f"  Listings updated: {updated_count}\n"
                f"  Total listings:   {created_count + updated_count}\n"
                f"\nAll listings are marked lgu_verified and ready for scoring."
            )
        )
