"""
seed_demo_data — populates Carles, Iloilo and Malay/Boracay, Aklan demo data.

Idempotent: uses update_or_create() for both destinations and listings.
Safe to run multiple times. Each run synchronises all approved metadata.

ScoreSnapshot and AIRecommendation are NOT seeded here.
They are generated by the scoring engine and AI advisor.

─────────────────────────────────────────────────────────────────────
LISTING DETAILS JSON SCHEMA
─────────────────────────────────────────────────────────────────────
The scoring engine reads these keys from Listing.details.
Do not rename keys without updating services.py.

work_spot:
  wifi_available        bool   — has Wi-Fi
  zoom_friendly         bool   — suitable for video calls
  power_outlets         bool   — has power outlets at seats
  wifi_speed_mbps       int|null — published speed in Mbps, null if unknown
  mobile_data_available bool   — mobile signal present

accommodation:
  monthly_rate_available bool  — monthly pricing is published
  has_wifi               bool  — Wi-Fi included
  has_desk               bool  — dedicated work desk
  has_kitchen            bool  — kitchen or kitchenette
  has_laundry            bool  — laundry access

service:
  service_type    str  — "clinic" | "hospital" | "police" | "pharmacy"
                          | "atm" | "laundry" | "grocery"
  contact_available bool — has listed contact/number
  has_safety_notes  bool — safety information is documented

transport:
  route_from_iloilo bool  — is the main Iloilo City → Carles route
  is_port           bool  — is a port or ferry terminal
  local_transport   bool  — is a local in-town option
  schedule_available bool — schedule or frequency is published
  fare_info         bool  — fare/cost information is available
  travel_time_hours float|null — approximate travel time from Iloilo City

attraction:
  island_hopping    bool  — island hopping or beach activity
  has_tour_operator bool  — tour operator or guide available
  activity_type     str   — "beach" | "island" | "food" | "nature"
                             | "culture" | "wellness" | "sandbar"
  has_community_event bool — community or seasonal event associated
─────────────────────────────────────────────────────────────────────
"""

from django.core.management.base import BaseCommand
from apps.destinations.models import Destination
from apps.listings.models import Listing


# ── Destination metadata ──────────────────────────────────────────────────────

DESTINATIONS = [
    {
        "lookup": {"name": "Carles"},
        "defaults": {
            "slug": "carles",
            "province": "Iloilo",
            "municipality": "Carles",
            "latitude": "11.572000",
            "longitude": "123.134000",
            "default_zoom": 13,
            "description": (
                "Carles is a municipality in the northern tip of Iloilo province, "
                "known for the Gigantes Islands — a group of islands and islets "
                "renowned for pristine beaches, rock formations, and rich marine life. "
                "The pilot destination for NomadReady PH."
            ),
        },
    },
    {
        "lookup": {"name": "Malay / Boracay"},
        "defaults": {
            "slug": "malay-boracay",
            "province": "Aklan",
            "municipality": "Malay",
            "latitude": "11.980000",
            "longitude": "121.919000",
            "default_zoom": 13,
            "description": (
                "Malay is a municipality in Aklan province that includes Boracay Island, "
                "one of the Philippines' most renowned beach destinations. "
                "With established tourism infrastructure, it demonstrates strong digital "
                "nomad potential while retaining realistic gaps in healthcare depth and "
                "long-stay affordability. Demo destination for NomadReady PH."
            ),
        },
    },
]


# ── Carles listings ───────────────────────────────────────────────────────────

CARLES_LISTINGS = [
    # ── WORK SPOTS ────────────────────────────────────────────────
    {
        "name": "Carles Port Café",
        "category": Listing.Category.WORK_SPOT,
        "type": "cafe",
        "address": "Port Area, Carles, Iloilo",
        "latitude": "11.5170",
        "longitude": "123.1150",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "wifi_available": True,
            "zoom_friendly": True,
            "power_outlets": True,
            "wifi_speed_mbps": 25,
            "mobile_data_available": True,
        },
    },
    {
        "name": "Isla Work Lounge",
        "category": Listing.Category.WORK_SPOT,
        "type": "lounge",
        "address": "Carles Town Proper, Iloilo",
        "latitude": "11.5155",
        "longitude": "123.1180",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "wifi_available": True,
            "zoom_friendly": True,
            "power_outlets": True,
            "wifi_speed_mbps": 20,
            "mobile_data_available": True,
        },
    },
    {
        "name": "Gigantes Gateway Inn Lobby",
        "category": Listing.Category.WORK_SPOT,
        "type": "hotel_lobby",
        "address": "Gigantes Islands, Carles, Iloilo",
        "latitude": "11.6600",
        "longitude": "123.1980",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "wifi_available": True,
            "zoom_friendly": False,
            "power_outlets": True,
            "mobile_data_available": True,
        },
    },
    # ── ACCOMMODATIONS ────────────────────────────────────────────
    {
        "name": "Carles Bay Homestay",
        "category": Listing.Category.ACCOMMODATION,
        "type": "homestay",
        "address": "Carles Bay Area, Iloilo",
        "latitude": "11.5140",
        "longitude": "123.1120",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "monthly_rate_available": True,
            "has_wifi": True,
            "has_desk": False,
            "has_kitchen": False,
            "has_laundry": False,
        },
    },
    {
        "name": "Gigantes Gateway Pension",
        "category": Listing.Category.ACCOMMODATION,
        "type": "pension",
        "address": "Gigantes Islands, Carles, Iloilo",
        "latitude": "11.6590",
        "longitude": "123.1970",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "monthly_rate_available": False,
            "has_wifi": True,
            "has_desk": False,
            "has_kitchen": False,
            "has_laundry": False,
        },
    },
    {
        "name": "Island Stay Carles",
        "category": Listing.Category.ACCOMMODATION,
        "type": "guesthouse",
        "address": "Carles Town Proper, Iloilo",
        "latitude": "11.5162",
        "longitude": "123.1165",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "monthly_rate_available": True,
            "has_wifi": True,
            "has_desk": False,
            "has_kitchen": False,
            "has_laundry": False,
        },
    },
    # ── SERVICES ──────────────────────────────────────────────────
    {
        "name": "Carles Municipal Health Office",
        "category": Listing.Category.SERVICE,
        "type": "clinic",
        "address": "Municipal Hall Compound, Carles, Iloilo",
        "latitude": "11.5168",
        "longitude": "123.1172",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "service_type": "clinic",
            "contact_available": True,
            "has_safety_notes": False,
        },
    },
    {
        "name": "Carles Police Station",
        "category": Listing.Category.SERVICE,
        "type": "police",
        "address": "Carles, Iloilo",
        "latitude": "11.5172",
        "longitude": "123.1175",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "service_type": "police",
            "contact_available": True,
            "has_safety_notes": False,
        },
    },
    {
        "name": "Local Pharmacy",
        "category": Listing.Category.SERVICE,
        "type": "pharmacy",
        "address": "Carles Town Proper, Iloilo",
        "latitude": "11.5160",
        "longitude": "123.1160",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "service_type": "pharmacy",
            "contact_available": False,
            "has_safety_notes": False,
        },
    },
    {
        "name": "Laundry Service",
        "category": Listing.Category.SERVICE,
        "type": "laundry",
        "address": "Carles Town Proper, Iloilo",
        "latitude": "11.5158",
        "longitude": "123.1158",
        "verification_status": Listing.VerificationStatus.DRAFT,
        "details": {
            "service_type": "laundry",
            "contact_available": False,
            "has_safety_notes": False,
        },
    },
    {
        "name": "ATM near town center",
        "category": Listing.Category.SERVICE,
        "type": "atm",
        "address": "Carles Town Center, Iloilo",
        "latitude": "11.5165",
        "longitude": "123.1168",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "service_type": "atm",
            "contact_available": False,
            "has_safety_notes": False,
        },
    },
    # ── TRANSPORT ─────────────────────────────────────────────────
    {
        "name": "Iloilo City to Carles van route",
        "category": Listing.Category.TRANSPORT,
        "type": "van_route",
        "address": "Tagbak Terminal, Iloilo City to Carles",
        "latitude": "11.5200",
        "longitude": "123.1100",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "route_from_iloilo": True,
            "is_port": False,
            "local_transport": False,
            "schedule_available": True,
            "fare_info": True,
        },
    },
    {
        "name": "Bancal Port",
        "category": Listing.Category.TRANSPORT,
        "type": "port",
        "address": "Bancal, Carles, Iloilo",
        "latitude": "11.5210",
        "longitude": "123.1090",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "route_from_iloilo": False,
            "is_port": True,
            "local_transport": False,
            "schedule_available": True,
            "fare_info": True,
        },
    },
    {
        "name": "Tricycle local transport",
        "category": Listing.Category.TRANSPORT,
        "type": "tricycle",
        "address": "Carles Town Proper, Iloilo",
        "latitude": "11.5163",
        "longitude": "123.1163",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "route_from_iloilo": False,
            "is_port": False,
            "local_transport": False,
            "schedule_available": False,
            "fare_info": True,
        },
    },
    {
        "name": "Boat route to Gigantes Islands",
        "category": Listing.Category.TRANSPORT,
        "type": "boat",
        "address": "Bancal Port, Carles to Gigantes Islands",
        "latitude": "11.5215",
        "longitude": "123.1085",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "route_from_iloilo": False,
            "is_port": False,
            "local_transport": False,
            "schedule_available": True,
            "fare_info": True,
        },
    },
    # ── ATTRACTIONS ───────────────────────────────────────────────
    {
        "name": "Gigantes Islands",
        "category": Listing.Category.ATTRACTION,
        "type": "island",
        "address": "Gigantes Islands, Carles, Iloilo",
        "latitude": "11.6650",
        "longitude": "123.2000",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "island_hopping": True,
            "has_tour_operator": True,
            "activity_type": "island",
            "has_community_event": False,
        },
    },
    {
        "name": "Cabugao Gamay Island",
        "category": Listing.Category.ATTRACTION,
        "type": "island",
        "address": "Cabugao Gamay, Gigantes, Carles, Iloilo",
        "latitude": "11.6700",
        "longitude": "123.2050",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "island_hopping": True,
            "has_tour_operator": False,
            "activity_type": "beach",
            "has_community_event": False,
        },
    },
    {
        "name": "Bantigue Sandbar",
        "category": Listing.Category.ATTRACTION,
        "type": "sandbar",
        "address": "Bantigue Island, Carles, Iloilo",
        "latitude": "11.6580",
        "longitude": "123.1900",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "island_hopping": True,
            "has_tour_operator": False,
            "activity_type": "sandbar",
            "has_community_event": False,
        },
    },
    {
        "name": "Antonia Beach",
        "category": Listing.Category.ATTRACTION,
        "type": "beach",
        "address": "Antonia, Carles, Iloilo",
        "latitude": "11.6500",
        "longitude": "123.1850",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "island_hopping": False,
            "has_tour_operator": False,
            "activity_type": "beach",
            "has_community_event": True,
        },
    },
    {
        "name": "Seafood food experience",
        "category": Listing.Category.ATTRACTION,
        "type": "food",
        "address": "Carles Public Market, Iloilo",
        "latitude": "11.5155",
        "longitude": "123.1155",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "island_hopping": False,
            "has_tour_operator": False,
            "activity_type": "food",
            "has_community_event": True,
        },
    },
]


# ── Malay / Boracay listings ──────────────────────────────────────────────────
# Demonstration data only. Assets represent plausible LGU-documented infrastructure
# and are NOT representations of formally verified individual businesses.

MALAY_LISTINGS = [
    # ── WORK SPOTS ────────────────────────────────────────────────
    # 5 verified work spots: 3+ with published Wi-Fi speed, 3+ Zoom-friendly,
    # 3+ with power outlets, all with mobile data → achieves max internet score
    {
        "name": "Boracay Cowork Hub",
        "category": Listing.Category.WORK_SPOT,
        "type": "coworking",
        "address": "Station 2, Boracay Island, Malay, Aklan",
        "latitude": "11.9659",
        "longitude": "121.9241",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "wifi_available": True,
            "zoom_friendly": True,
            "power_outlets": True,
            "wifi_speed_mbps": 50,
            "mobile_data_available": True,
        },
    },
    {
        "name": "D'Mall Work Corner",
        "category": Listing.Category.WORK_SPOT,
        "type": "cafe",
        "address": "D'Mall, Station 2, Boracay Island, Malay, Aklan",
        "latitude": "11.9668",
        "longitude": "121.9234",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "wifi_available": True,
            "zoom_friendly": True,
            "power_outlets": True,
            "wifi_speed_mbps": 30,
            "mobile_data_available": True,
        },
    },
    {
        "name": "White Beach Laptop Lounge",
        "category": Listing.Category.WORK_SPOT,
        "type": "lounge",
        "address": "Station 1, Boracay Island, Malay, Aklan",
        "latitude": "11.9720",
        "longitude": "121.9198",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "wifi_available": True,
            "zoom_friendly": True,
            "power_outlets": True,
            "wifi_speed_mbps": 20,
            "mobile_data_available": True,
        },
    },
    {
        "name": "Station 1 Business Centre",
        "category": Listing.Category.WORK_SPOT,
        "type": "coworking",
        "address": "Station 1, Boracay Island, Malay, Aklan",
        "latitude": "11.9730",
        "longitude": "121.9190",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "wifi_available": True,
            "zoom_friendly": True,
            "power_outlets": True,
            "wifi_speed_mbps": 40,
            "mobile_data_available": True,
        },
    },
    {
        "name": "Caticlan Gateway Café",
        "category": Listing.Category.WORK_SPOT,
        "type": "cafe",
        "address": "Caticlan, Malay, Aklan",
        "latitude": "11.9277",
        "longitude": "121.9347",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "wifi_available": True,
            "zoom_friendly": False,
            "power_outlets": False,
            "wifi_speed_mbps": None,
            "mobile_data_available": True,
        },
    },
    # ── ACCOMMODATIONS ────────────────────────────────────────────
    # 5 verified; 4 with monthly rate, 4 with Wi-Fi, 3 with desk/kitchen/laundry
    {
        "name": "Discovery Shores Monthly Residence",
        "category": Listing.Category.ACCOMMODATION,
        "type": "resort_room",
        "address": "Station 1, Boracay Island, Malay, Aklan",
        "latitude": "11.9722",
        "longitude": "121.9196",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "monthly_rate_available": True,
            "has_wifi": True,
            "has_desk": True,
            "has_kitchen": False,
            "has_laundry": True,
        },
    },
    {
        "name": "Boracay Beach Club Long-Stay Suite",
        "category": Listing.Category.ACCOMMODATION,
        "type": "apartment",
        "address": "Station 2, Boracay Island, Malay, Aklan",
        "latitude": "11.9660",
        "longitude": "121.9240",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "monthly_rate_available": True,
            "has_wifi": True,
            "has_desk": True,
            "has_kitchen": True,
            "has_laundry": True,
        },
    },
    {
        "name": "Puka Shell Guesthouse",
        "category": Listing.Category.ACCOMMODATION,
        "type": "guesthouse",
        "address": "Puka Beach, Boracay Island, Malay, Aklan",
        "latitude": "12.0078",
        "longitude": "121.9215",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "monthly_rate_available": True,
            "has_wifi": True,
            "has_desk": False,
            "has_kitchen": False,
            "has_laundry": False,
        },
    },
    {
        "name": "Station 3 Long-Stay Inn",
        "category": Listing.Category.ACCOMMODATION,
        "type": "pension",
        "address": "Station 3, Boracay Island, Malay, Aklan",
        "latitude": "11.9607",
        "longitude": "121.9264",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "monthly_rate_available": True,
            "has_wifi": True,
            "has_desk": False,
            "has_kitchen": True,
            "has_laundry": True,
        },
    },
    {
        "name": "Caticlan Bay Pension",
        "category": Listing.Category.ACCOMMODATION,
        "type": "pension",
        "address": "Caticlan, Malay, Aklan",
        "latitude": "11.9275",
        "longitude": "121.9345",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "monthly_rate_available": False,
            "has_wifi": True,
            "has_desk": False,
            "has_kitchen": False,
            "has_laundry": False,
        },
    },
    # ── SERVICES ──────────────────────────────────────────────────
    # clinic + police + pharmacy + atm + laundry/grocery + safety notes
    {
        "name": "Boracay Health Center",
        "category": Listing.Category.SERVICE,
        "type": "clinic",
        "address": "Balabag, Boracay Island, Malay, Aklan",
        "latitude": "11.9651",
        "longitude": "121.9248",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "service_type": "clinic",
            "contact_available": True,
            "has_safety_notes": True,
        },
    },
    {
        "name": "Malay Police Station",
        "category": Listing.Category.SERVICE,
        "type": "police",
        "address": "Caticlan, Malay, Aklan",
        "latitude": "11.9272",
        "longitude": "121.9348",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "service_type": "police",
            "contact_available": True,
            "has_safety_notes": False,
        },
    },
    {
        "name": "Mercury Drug Boracay",
        "category": Listing.Category.SERVICE,
        "type": "pharmacy",
        "address": "D'Mall, Station 2, Boracay Island, Malay, Aklan",
        "latitude": "11.9666",
        "longitude": "121.9235",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "service_type": "pharmacy",
            "contact_available": True,
            "has_safety_notes": False,
        },
    },
    {
        "name": "BDO ATM D'Mall",
        "category": Listing.Category.SERVICE,
        "type": "atm",
        "address": "D'Mall, Station 2, Boracay Island, Malay, Aklan",
        "latitude": "11.9667",
        "longitude": "121.9236",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "service_type": "atm",
            "contact_available": False,
            "has_safety_notes": False,
        },
    },
    {
        "name": "Island Laundry and Grocery",
        "category": Listing.Category.SERVICE,
        "type": "laundry",
        "address": "Station 2, Boracay Island, Malay, Aklan",
        "latitude": "11.9662",
        "longitude": "121.9243",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "service_type": "laundry",
            "contact_available": False,
            "has_safety_notes": False,
        },
    },
    # ── TRANSPORT ─────────────────────────────────────────────────
    # main route + port + local + schedule + travel time
    {
        "name": "Manila / Iloilo to Caticlan Airport route",
        "category": Listing.Category.TRANSPORT,
        "type": "airport_route",
        "address": "Godofredo P. Ramos Airport, Caticlan, Malay, Aklan",
        "latitude": "11.9241",
        "longitude": "121.9530",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "route_from_iloilo": True,
            "is_port": False,
            "local_transport": False,
            "schedule_available": True,
            "fare_info": True,
            "travel_time_hours": 0.5,
        },
    },
    {
        "name": "Caticlan Jetty Port",
        "category": Listing.Category.TRANSPORT,
        "type": "port",
        "address": "Caticlan Jetty Port, Malay, Aklan",
        "latitude": "11.9265",
        "longitude": "121.9355",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "route_from_iloilo": False,
            "is_port": True,
            "local_transport": False,
            "schedule_available": True,
            "fare_info": True,
            "travel_time_hours": None,
        },
    },
    {
        "name": "Boracay E-Trike",
        "category": Listing.Category.TRANSPORT,
        "type": "e_trike",
        "address": "Boracay Island, Malay, Aklan",
        "latitude": "11.9655",
        "longitude": "121.9245",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "route_from_iloilo": False,
            "is_port": False,
            "local_transport": True,
            "schedule_available": False,
            "fare_info": True,
            "travel_time_hours": None,
        },
    },
    {
        "name": "Caticlan–Boracay Ferry",
        "category": Listing.Category.TRANSPORT,
        "type": "ferry",
        "address": "Caticlan Jetty to Cagban Pier, Boracay, Malay, Aklan",
        "latitude": "11.9450",
        "longitude": "121.9300",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "route_from_iloilo": False,
            "is_port": True,
            "local_transport": False,
            "schedule_available": True,
            "fare_info": True,
            "travel_time_hours": 0.25,
        },
    },
    {
        "name": "Kalibo Airport alternative route",
        "category": Listing.Category.TRANSPORT,
        "type": "airport_route",
        "address": "Kalibo International Airport to Caticlan, Aklan",
        "latitude": "11.6795",
        "longitude": "122.3759",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "route_from_iloilo": False,
            "is_port": False,
            "local_transport": False,
            "schedule_available": True,
            "fare_info": True,
            "travel_time_hours": 2.0,
        },
    },
    # ── ATTRACTIONS ───────────────────────────────────────────────
    # 6 verified attractions: island hop, tour operator, beach, food, culture, events
    {
        "name": "White Beach Boracay",
        "category": Listing.Category.ATTRACTION,
        "type": "beach",
        "address": "White Beach, Boracay Island, Malay, Aklan",
        "latitude": "11.9663",
        "longitude": "121.9230",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "island_hopping": False,
            "has_tour_operator": True,
            "activity_type": "beach",
            "has_community_event": True,
        },
    },
    {
        "name": "Puka Shell Beach",
        "category": Listing.Category.ATTRACTION,
        "type": "beach",
        "address": "Puka Beach, Boracay Island, Malay, Aklan",
        "latitude": "12.0078",
        "longitude": "121.9215",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "island_hopping": False,
            "has_tour_operator": False,
            "activity_type": "beach",
            "has_community_event": True,
        },
    },
    {
        "name": "Bulabog Beach Kitesurfing",
        "category": Listing.Category.ATTRACTION,
        "type": "activity",
        "address": "Bulabog Beach, Boracay Island, Malay, Aklan",
        "latitude": "11.9650",
        "longitude": "121.9295",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "island_hopping": False,
            "has_tour_operator": True,
            "activity_type": "wellness",
            "has_community_event": False,
        },
    },
    {
        "name": "Ariel's Point Island Hop",
        "category": Listing.Category.ATTRACTION,
        "type": "island",
        "address": "Buruanga, Aklan (from Boracay)",
        "latitude": "11.8978",
        "longitude": "121.8600",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "island_hopping": True,
            "has_tour_operator": True,
            "activity_type": "island",
            "has_community_event": False,
        },
    },
    {
        "name": "D'Talipapa Seafood Market",
        "category": Listing.Category.ATTRACTION,
        "type": "food",
        "address": "Station 2, Boracay Island, Malay, Aklan",
        "latitude": "11.9670",
        "longitude": "121.9250",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "island_hopping": False,
            "has_tour_operator": False,
            "activity_type": "food",
            "has_community_event": True,
        },
    },
    {
        "name": "Paraw Sailing Boracay",
        "category": Listing.Category.ATTRACTION,
        "type": "activity",
        "address": "White Beach, Boracay Island, Malay, Aklan",
        "latitude": "11.9656",
        "longitude": "121.9228",
        "verification_status": Listing.VerificationStatus.LGU_VERIFIED,
        "details": {
            "island_hopping": False,
            "has_tour_operator": True,
            "activity_type": "culture",
            "has_community_event": True,
        },
    },
]


# ── Listings map ──────────────────────────────────────────────────────────────

LISTINGS_BY_DESTINATION = {
    "Carles": CARLES_LISTINGS,
    "Malay / Boracay": MALAY_LISTINGS,
}


# ── Command ───────────────────────────────────────────────────────────────────

class Command(BaseCommand):
    help = "Seed Carles and Malay/Boracay demo data for NomadReady PH. Idempotent."

    def handle(self, *args, **options):
        total_created = 0
        total_updated = 0

        for dest_spec in DESTINATIONS:
            name = dest_spec["lookup"]["name"]
            meta = dest_spec["defaults"]

            # update_or_create ensures slug + coordinates are always in sync
            # even when re-run against an already-seeded database.
            destination, created = Destination.objects.update_or_create(
                name=name,
                defaults=meta,
            )
            action = "Created" if created else "Updated"
            self.stdout.write(f"{action} destination: {destination}")

            listings = LISTINGS_BY_DESTINATION[name]
            dest_created = 0
            dest_updated = 0

            for data in listings:
                _, was_created = Listing.objects.update_or_create(
                    destination=destination,
                    name=data["name"],
                    defaults={
                        "category": data["category"],
                        "type": data["type"],
                        "address": data["address"],
                        "latitude": data["latitude"],
                        "longitude": data["longitude"],
                        "details": data["details"],
                        "verification_status": data["verification_status"],
                    },
                )
                if was_created:
                    dest_created += 1
                else:
                    dest_updated += 1

            total_created += dest_created
            total_updated += dest_updated
            self.stdout.write(
                f"  Listings — created: {dest_created}, updated: {dest_updated}"
            )

        self.stdout.write(
            self.style.SUCCESS(
                f"\nSeed complete.\n"
                f"  Total listings created: {total_created}\n"
                f"  Total listings updated: {total_updated}\n"
                f"  Total listings:         {total_created + total_updated}\n"
            )
        )
