# Generated by Django 4.2.30 on 2026-06-12 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('work_spot', 'Work Spot'), ('accommodation', 'Accommodation'), ('service', 'Service'), ('transport', 'Transport'), ('attraction', 'Attraction')], max_length=50)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('details', models.JSONField(default=dict)),
                ('verification_status', models.CharField(choices=[('draft', 'Draft'), ('lgu_verified', 'LGU Verified'), ('needs_update', 'Needs Update')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='destinations.destination')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
