# Generated by Django 4.2.30 on 2026-06-12 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoring', '0001_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('affected_category', models.CharField(max_length=100)),
                ('recommendation', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('reason', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='destinations.destination')),
                ('score_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='scoring.scoresnapshot')),
            ],
            options={
                'ordering': ['priority', '-generated_at'],
            },
        ),
    ]
