# Generated by Django 4.2.30 on 2026-06-12 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_label', models.CharField(max_length=100)),
                ('internet_work_score', models.IntegerField()),
                ('accommodation_score', models.IntegerField()),
                ('safety_services_score', models.IntegerField()),
                ('transport_score', models.IntegerField()),
                ('tourism_lifestyle_score', models.IntegerField()),
                ('strongest_category', models.CharField(max_length=100)),
                ('weakest_category', models.CharField(max_length=100)),
                ('top_gaps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_snapshots', to='destinations.destination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
