# Generated by Django 4.2.30 on 2026-06-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
