# Generated by Django 4.2.30 on 2026-06-29 22:58

from django.db import migrations, models
<<<<<<< HEAD
=======
from django.db.models.functions import Lower
>>>>>>> origin/main


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
<<<<<<< HEAD
=======
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.UniqueConstraint(Lower('name'), name='destination_name_ci_unique'),
        ),
>>>>>>> origin/main
    ]
